var arrows = document.querySelector('#arrows');
var back = document.querySelector('#back');
var next = document.querySelector('#next');
var error = document.querySelector('#error');
var inputs = document.querySelectorAll('input');
var selected;
var skill = [];
var skillLimit;
var skillGiven;
var skillNumber;
var tool = [];
var toolLimit;
var toolGiven;
var artisan = [];
var artisanLimit;
var artisanNumber;
var gaming = [];
var gamingLimit;
var gamingNumber;
var music = [];
var musicLimit;
var musicNumber;
var expertise = [];
var expertiseLimit;
var expertiseNumber;
var language = [];
var languageLimit;
var languageGiven;
var languageNumber;
var points;
var abilities = {};
var mods = {};
var scores = {};
var completion = [];